name: test-che

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -s "https://www.12365auto.com/all/index_1.shtml" | grep -oP 'news_l_b.*' | head -c 3000
